"""add_pooled_questions_table

Revision ID: acc28b1fcb32
Revises: cef0b7cb1813
Create Date: 2026-10-02 22:58:36.956396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc28b1fcb32'
down_revision: Union[str, Sequence[str], None] = 'cef0b7cb1813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pooled_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('source_draft_id', sa.Uuid(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_option_index', sa.Integer(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_pooled_questions_added_by_users')),
    sa.ForeignKeyConstraint(['source_draft_id'], ['question_drafts.id'], name=op.f('fk_pooled_questions_source_draft_id_question_drafts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_pooled_questions_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_pooled_questions_unit_id_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pooled_questions'))
    )
    op.create_index(op.f('ix_pooled_questions_added_by'), 'pooled_questions', ['added_by'], unique=False)
    op.create_index(op.f('ix_pooled_questions_bloom_level'), 'pooled_questions', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_pooled_questions_difficulty'), 'pooled_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_pooled_questions_question_type'), 'pooled_questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_pooled_questions_source_draft_id'), 'pooled_questions', ['source_draft_id'], unique=False)
    op.create_index(op.f('ix_pooled_questions_subject_id'), 'pooled_questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_pooled_questions_unit_id'), 'pooled_questions', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pooled_questions_unit_id'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_subject_id'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_source_draft_id'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_question_type'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_difficulty'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_bloom_level'), table_name='pooled_questions')
    op.drop_index(op.f('ix_pooled_questions_added_by'), table_name='pooled_questions')
    op.drop_table('pooled_questions')
    # ### end Alembic commands ###
